#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','I','.',' ',
        '-','I','.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',
        ' ','-','f','P','I','C',' ','-','D','O','P','E','N','S','S','L','_','P',
        'I','C',' ','-','D','O','P','E','N','S','S','L','_','T','H','R','E','A',
        'D','S',' ','-','D','_','R','E','E','N','T','R','A','N','T',' ','-','D',
        'D','S','O','_','D','L','F','C','N',' ','-','D','H','A','V','E','_','D',
        'L','F','C','N','_','H',' ','-','D','L','_','E','N','D','I','A','N',' ',
        '-','g',' ','-','O','2',' ','-','f','s','t','a','c','k','-','p','r','o',
        't','e','c','t','o','r','-','s','t','r','o','n','g',' ','-','W','f','o',
        'r','m','a','t',' ','-','W','e','r','r','o','r','=','f','o','r','m','a',
        't','-','s','e','c','u','r','i','t','y',' ','-','D','_','F','O','R','T',
        'I','F','Y','_','S','O','U','R','C','E','=','2',' ','-','W','l',',','-',
        'z',',','r','e','l','r','o',' ','-','W','a',',','-','-','n','o','e','x',
        'e','c','s','t','a','c','k',' ','-','W','a','l','l',' ','-','D','O','P',
        'E','N','S','S','L','_','B','N','_','A','S','M','_','M','O','N','T',' ',
        '-','D','O','P','E','N','S','S','L','_','B','N','_','A','S','M','_','G',
        'F','2','m',' ','-','D','S','H','A','1','_','A','S','M',' ','-','D','S',
        'H','A','2','5','6','_','A','S','M',' ','-','D','S','H','A','5','1','2',
        '_','A','S','M',' ','-','D','A','E','S','_','A','S','M',' ','-','D','B',
        'S','A','E','S','_','A','S','M',' ','-','D','G','H','A','S','H','_','A',
        'S','M','\0'
    };
    #define PLATFORM "platform: debian-armel"
    #define DATE "built on: Fri Mar  3 16:28:42 2017"
#endif
