DEBUG := n
TARGET := second_spi_flash_hw
OBJS := ast_second_spi_flash.o 

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/second_spi_flash

-include ${TOOLDIR}/rules/Rules.make.drivers
