--- linux/arch/arm/mach-astevb/include/mach/serial.h	2019-11-04 15:11:36.408883920 +0800
+++ new_linux/arch/arm/mach-astevb/include/mach/serial.h	2019-11-04 18:35:54.714835348 +0800
@@ -31,15 +31,15 @@
 
 #if !defined(CONFIG_SOC_AST2530)
 #define SERIAL_PORT_DFNS    \
- {0, BASE_BAUD, AST_UART1_BASE, IRQ_UARTINT0, STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART1_VA_BASE, 2},   \
- {0, BASE_BAUD, AST_UART2_BASE, IRQ_UARTINT1, STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART2_VA_BASE, 2},   \
+ {0, BASE_BAUD, AST_UART1_BASE, IRQ_UARTINT0, UPF_SKIP_TEST, 0, UPIO_MEM32, (void *) AST_UART1_VA_BASE, 2},   \
+ {0, BASE_BAUD, AST_UART2_BASE, IRQ_UARTINT1, UPF_SKIP_TEST, 0, UPIO_MEM32, (void *) AST_UART2_VA_BASE, 2},   \
  {0, BASE_BAUD, AST_UART3_BASE, IRQ_UARTINT2, STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART3_VA_BASE, 2},   \
  {0, BASE_BAUD, AST_UART4_BASE, IRQ_UARTINT3, STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART4_VA_BASE, 2},   \
  {0, BASE_BAUD, AST_UART5_BASE, IRQ_UARTINT4, STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART5_VA_BASE, 2},
 #else
 #define SERIAL_PORT_DFNS    \
- {0, BASE_BAUD, AST_UART1_BASE,  IRQ_UARTINT0,  STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART1_VA_BASE, 2},   \
- {0, BASE_BAUD, AST_UART2_BASE,  IRQ_UARTINT1,  STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART2_VA_BASE, 2},   \
+ {0, BASE_BAUD, AST_UART1_BASE,  IRQ_UARTINT0,  UPF_SKIP_TEST, 0, UPIO_MEM32, (void *) AST_UART1_VA_BASE, 2},   \
+ {0, BASE_BAUD, AST_UART2_BASE,  IRQ_UARTINT1,  UPF_SKIP_TEST, 0, UPIO_MEM32, (void *) AST_UART2_VA_BASE, 2},   \
  {0, BASE_BAUD, AST_UART3_BASE,  IRQ_UARTINT2,  STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART3_VA_BASE, 2},   \
  {0, BASE_BAUD, AST_UART4_BASE,  IRQ_UARTINT3,  STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART4_VA_BASE, 2},   \
  {0, BASE_BAUD, AST_UART5_BASE,  IRQ_UARTINT4,  STD_COM_FLAGS, 0, UPIO_MEM32, (void *) AST_UART5_VA_BASE, 2},   \
