DEBUG  := n
TARGET := snoop_hw
OBJS   := snoopmain_hw.o

EXTRA_CFLAGS += -I${SPXINC}/global
EXTRA_CFLAGS += -I${SPXINC}/helper
EXTRA_CFLAGS += -I${SPXINC}/reset
EXTRA_CFLAGS += -I${SPXINC}/snoop

-include ${TOOLDIR}/rules/Rules.make.drivers


