#!/bin/sh

set -e

if [ x$1 = "xpurge" ]; then
	echo You may want to delete the generated stunnel.pem file
	echo in /etc/ssl/certs.

        # Remove chroot dir if present. It may contain logfiles
        rm -rf /var/lib/stunnel4 || true

        # Log files must be removed on purge (Policy 10.8)
        rm -f /var/log/stunnel4/stunnel.log* || true
        rmdir /var/log/stunnel4 || true
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d stunnel4 remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section

