DEBUG    := n
TARGET   := pwmtach_hw
OBJS      := pwmtachmain_hw.o 

EXTRA_CFLAGS += -I${SPXINC}/global 
EXTRA_CFLAGS += -I${SPXINC}/pwmtach
EXTRA_CFLAGS += -I${SPXINC}/helper

-include ${TOOLDIR}/rules/Rules.make.drivers

