/*****************************************************************
 **                                                             **
 **     (C) Copyright 2009-2015, American Megatrends Inc.       **
 **                                                             **
 **             All Rights Reserved.                            **
 **                                                             **
 **         5555 Oakbrook Pkwy Suite 200, Norcross,             **
 **                                                             **
 **         Georgia - 30093, USA. Phone-(770)-246-8600.         **
 **                                                             **
 ****************************************************************/

#include <linux/module.h>
#include <linux/kernel.h>       /* printk()*/
#include <linux/version.h>
#if (LINUX_VERSION_CODE <  KERNEL_VERSION(3,0,0))
#ifndef AUTOCONF_INCLUDED
#include <linux/config.h>
#endif
#endif
#include <linux/errno.h>
#include <linux/sched.h>
#include <linux/kernel.h>
#include <linux/interrupt.h>
#include <asm/uaccess.h>
#include "driver_hal.h"
#include "reset.h"

#define MAX_LPCRESET_HW		1
#define LPC_RST_INTR_EN         1<<2
#define LPC_RST_IRQ_ADDR	IRQ_SIO_PSR
#define LPCRESET_HW_DEV_NAME 	"lpcreset_hw"

static int lpcreset_irq_requested = 0;

static int m_dev_id = 0;

static reset_hal_operations_t lpcreset_hw_ops = {
};

static reset_core_funcs_t *preset_core_funcs;

static hw_hal_t hw_hal = {
	.dev_type = EDEV_TYPE_RESET,
        .owner = THIS_MODULE,
        .devname = LPCRESET_HW_DEV_NAME,
        .num_instances = MAX_LPCRESET_HW,
        .phal_ops = (void *)&lpcreset_hw_ops
};

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3,0,0))
static int lpcreset_hw_init(void);
static void lpcreset_hw_exit(void);
#else
static int __init lpcreset_hw_init(void);
static void __exit lpcreset_hw_exit(void);
#endif
static void enable_lpcreset_interrupt(void);
static void disable_lpcreset_interrupt(void);
static int get_lpcreset_irq(void);


/*****************************************************************************************/

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3,0,0))
static int lpcreset_hw_init(void)
#else
static int __init
lpcreset_hw_init(void)
#endif
{
	int err = 0, ret = 0;

	if ((ret = register_hw_hal_module ( &hw_hal, (void**)&preset_core_funcs)) < 0)
	{
		printk("Failed to initialize the LPCRESET HW module\n");
		return -1;
	}
	m_dev_id = ret;

	err = get_lpcreset_irq();
	if (err < 0)
	{
		ret = -EBUSY;
		goto fail;
	}
	lpcreset_irq_requested = 1;

	enable_lpcreset_interrupt();

	printk("LPCreset HW Driver, (c) 2009-2015 American Megatrends Inc.\n");
	return ret;

fail:
	lpcreset_hw_exit();
	return ret;	
}

#if (LINUX_VERSION_CODE >= KERNEL_VERSION(3,0,0))
static void lpcreset_hw_exit(void)
#else
static void __exit
lpcreset_hw_exit(void)
#endif
{
	disable_lpcreset_interrupt();

	if (lpcreset_irq_requested)
	{
		free_irq(LPC_RST_IRQ_ADDR, (void*) ("lpcreset_irq"));
		lpcreset_irq_requested = 0;
	}

	if (0 != unregister_hw_hal_module (EDEV_TYPE_RESET, m_dev_id))
        {
                printk("Failed to unregister LPCRESET HW module\n");
		return;
        }	

	printk("LPCreset HW module released\n");
}


#if (LINUX_VERSION_CODE >=  KERNEL_VERSION(2,6,24))
irqreturn_t lpcreset_handler ( int irq, void *dev_id )
#else
irqreturn_t lpcreset_handler ( int irq, void *dev_id, struct pt_regs *regs )
#endif
{
        unsigned char lpcreset_intr_info;
        //int err = 0;

        lpcreset_intr_info = *(unsigned char*) (SE_PILOT_SPEC_VA_BASE + 0x23);

        /* If interrupt not generated by RESET edge, return */
        if (lpcreset_intr_info & 0x02)
        {
            //printk(KERN_INFO "LPC Reset Interrupt\n");
            enable_lpcreset_interrupt();
            preset_core_funcs->process_reset_intr (m_dev_id);
        }
        else
        {
            return (IRQ_NONE);
        }

        return (IRQ_HANDLED);
}

static void 
enable_lpcreset_interrupt(void)
{
        unsigned char intr_s;

        intr_s = *(unsigned char *)(SE_PILOT_SPEC_VA_BASE + 0x23);
        *(unsigned char *)(SE_PILOT_SPEC_VA_BASE + 0x23) = intr_s;
        intr_s = intr_s | LPC_RST_INTR_EN;
        *(unsigned char *)(SE_PILOT_SPEC_VA_BASE + 0x23) = intr_s;
}

static void 
disable_lpcreset_interrupt(void)
{
        unsigned char intr_s;

        intr_s = *(unsigned char *)(SE_PILOT_SPEC_VA_BASE + 0x23);
        intr_s = intr_s & (~LPC_RST_INTR_EN);
        *(unsigned char *)(SE_PILOT_SPEC_VA_BASE + 0x23) = intr_s;
}

static int
get_lpcreset_irq(void)
{
        int err;

        #if (LINUX_VERSION_CODE >=  KERNEL_VERSION(2,6,24))
                err = request_irq(LPC_RST_IRQ_ADDR, lpcreset_handler, IRQF_SHARED, "lpcreset", (void*)("lpcreset_irq"));
        #else
                err = request_irq(LPC_RST_IRQ_ADDR, lpcreset_handler, SA_SHIRQ, "lpcreset", (void*)("lpcreset_irq"));
        #endif

        if (err < 0)
                printk("failed to request irq %d (err %d)", LPC_RST_IRQ_ADDR, err);

        return err;
}

/***************************************************************************************/

module_init (lpcreset_hw_init);
module_exit (lpcreset_hw_exit);

MODULE_AUTHOR("American Megatrends Inc");
MODULE_DESCRIPTION("This is LPCRESET HW driver module.");
MODULE_LICENSE("GPL");

